"""remove otp and isvalid field

Revision ID: e335fbc43aff
Revises: 005579e83426
Create Date: 2026-03-12 22:48:49.674867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e335fbc43aff'
down_revision: Union[str, Sequence[str], None] = '005579e83426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp')
    op.drop_column('user', 'isvalid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isvalid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
